version: "3.2"
services:
   nginx:
    image: nginx:latest
    container_name: nginx
    links:
       - consul
    ports:
       - "8080:8080"
    networks:
        - multired_net
   consul:
    command: -server -bootstrap -advertise ${HOST_IP}
    image: progrium/consul
    container_name: consul
    logging:
        driver: json-file
    ports:
      - "8500:8500"
    networks:
        - multired_net
    environment:
      - HOST_IP=$HOST_IP
   rabbitmq:
    command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - multired_net
   multiplication:
    image: multiplication:latest
    logging:
       driver: json-file
    depends_on:
       - rabbitmq
       - consul
       - nginx
    networks:
        - multired_net
    

networks:
  multired_net:
    driver: bridge
